//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.13 at 04:10:24 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://action.trm.services.generic.action.superfinanciera.nexura.sc.com.co/")
package com.ceiba.parking.wsdl;
